<a href="https://colab.research.google.com/github/PARTH566/ML_parth_2024/blob/main/Copy_of_Introduction_To_Python_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **What is Python ?**
> Python is a popular, open source high-level programming language released in 1991. It is a platform independent ***interpreted*** language.

## **What can it be used for ?**
*   Data Science
*   Machine Learning & AI
*   Web Development (Server Side)
*   GUI Development
*   Scientific & Numeric Programming

## **Why Python ?**
1.   Simple, easy-to-learn syntax
2.  There exists inbuilt functions for almost all of the frequently used concepts.
3.   Supports a wide array of third-party modules and libraries


# **Hello World! in C++**
```
#include <stdio.h>

int main(){
    cout<<"Hello World!"<<endl;
    return 0;
}
```

# **Python vs. C/C++**

1. No  `;` in Python!

Unlike C/C++ a python statement does not require a `;` to terminate. But, every python statement must be placed in a new line.

2. No `{ }` in Python!

Python does not use `{ }` to define blocks in code like in C/C++. Instead, python brings a new headache of ***Indentation***.

## Writing our first program



In [ ]:
#Script begins from here
print('Hello, World')
# Thats all, no imports required

Hello, World


* The `print()` function also takes two other optional arguements:
1. **sep** = *'separator'* : Specify how to separate two objects. Set to ' ' by default.
2. **end** = *'end'* : Specify what to print at the end of line. Set to '\n' by default.

In [ ]:
print('Hello', 'World', sep="")
print('Hello', 'World')

HelloWorld


In [ ]:
print("Hello", end="")
print("World!")

In [1]:
#Writing two statements in the same line is invalid in python but not in C/C++
a=1
b=5
print(a+b)

6


# **Indentation**

1. Python uses the idea of indentation to highlight the blocks of code. While in C/C++ or other programming languages it is just for the sake of code readability.

2. Wrong indentation can cause **undetectable** errors to your code.


In [ ]:
# Python program to show indentation
x=10
if x>13:
  print('Hello')
else:
  print('World')
print('This is indentation')

World
This is indentation


## **Variables in Python**

*   Python has no command to declare variable. Like 'int x=10;'.
*   But the rules for variable naming are similar to that in C/C++. A variable name can contain only alphanumeric characters and underscores and cannot start with a number. They are case-sensitive.
*  Variables do not require a data type when initialized and data type of any variable can be changed as required.
* A variable is created whenever it is initialized.


In [ ]:
x=222222222222222222222222222222222222222222222222222222222222222
print(x)

222222222222222222222222222222222222222222222222222222222222222




*   Multiple variables can be initialized in a single statement. For eg.


In [ ]:
x,y,z=1, 2.2, "Hello"
print(x,y,z)

1 2.2 Hello


# Operators in Python

## **Arithmetic Operators**

Operator | Name
--- | ---
`+` | Addition
`-` | Subtraction
`*` | Multiplication
`/` | Division
`%` | Modulus
`**`| Exponentiation (Power)
`//`| Floor division

In [ ]:
# Arithmetic Operators
x=10
y=4
print(x+y) # Addition Operator
print(x-y) # Subtraction Operator
print(x*y) # Multiplication Operator
print(x/y) # Division Operator
print(x//y) # Floor Division Operator
print(x**y) # pow(x,y)

14
6
40
2.5
2
10000


## **Assignment Operators**

Operator &emsp; &emsp;| Use  &emsp;  &emsp;  &emsp;   | Equivalent
---- |----------|------------
`=`  | 	x = 7   |   x = 7
`+=` |	x += 7  | 	x = x + 7
`-=` |	x -= 7  | 	x = x - 7
`*=` |	x \*= 7 |	x = x * 7
`/=` |	x /= 7  |	x = x / 7
`%=` |	x %= 7  |	x = x % 7
`//=`|	x //= 7 |	x = x // 7
`**=`|	x **= 7 |	x = x ** 7
`&=` |	x &= 7  |	x = x & 7
`\|=`|	x \|= 7 |   x = x \| 7
`^=` |	x ^= 7  |	x = x ^ 7
`>>=`|	x >>= 7 |	x = x >> 7
`<<=`|	x <<= 7 |	x = x << 7

In [ ]:
# Assignment Operators
x = 4;
x **= 3;
print(x)

64


## **Python Logical Operators**

* In python logical operators are used directly by name. We do not have `&&` and `||` in python.

Operator | Description | Example
---|---|---
`and` | True if both conditions are true |	x < 4 and  x < 14
`or`	| True if any one of the condition is true |	x < 10 or x > 20
`not`	| Returns False if the result is True and vice versa &nbsp;|	not(x < 5 and x < 10)

In [ ]:
# Logical Operators
# In python we use logical operators directly by their name instead of && and ||

x=10
if x>5 and x<15:
  print('Hello')
if x>15 or x<20:
  print('World')

Hello
World


## **Taking input in python**

Taking input in python is fairly easy and we use the input() function to do so

In [ ]:
name = input("What is your name ? ")
print("Welcome " + name)

What is your name ? Dhruv
Welcome Dhruv


In [ ]:
x= input()
print(x, type(x)) # Input is taken by default in string type, so we need to typecast.

15
15 <class 'str'>


##**Type Casting**

* Type casting can be used to convert variables from one type to another.

In [ ]:
x = float(input("Enter a number: "))
print(x + 10)

Enter a number: 15
25.0


Type casting can be mainly done with these data type function:
* `str()` : Convert int or float type to string
* `int()` : Convert string or float type to integer
* `float()` : Convert string or int type to float

In [ ]:
x_int = 10
x_str = "12"
x_float = 14.7

# str()
print("Result: " + str(x_int));
print("Result: " + str(x_float));
print('')

# int()
print(3 + x_float)
print(3 + int(x_float))
print(4 + int(x_str), type(int(x_str)))
print('')

# float()
print(1.2 + float(x_int), type(float(x_int)))
print(1.3 + float(x_str))
print('')

# original variable types
print(type(x_int), type(x_str), type(x_float))

Result: 10
Result: 14.7

17.7
17
16 <class 'int'>

11.2 <class 'float'>
13.3

<class 'int'> <class 'str'> <class 'float'>


* One must note that the type casting functions do not change the type of the original variable but instead return a new value of the desired type. To change type of the original variable one can use,

In [ ]:
x = "10"
print(type(x))
y = int(x)
print(type(x), type(y))

<class 'str'>
<class 'str'> <class 'int'>


## Coding Problem - 1

In [2]:
# Write a program that takes a user's name and age as input and prints a Hello World! message that includes their name and age.
name = input("Enter your name: ")
print("")
age = input("Enter you Age: ")
print("Hello " + name + "(Age: " + age + ")")

Enter your name: Parth

Enter you Age: 18
Hello Parth(Age: 18)


In [5]:
# Create a program that swaps the values of two variables without using a third variable.
a = 5
b = 3
a += b
b = a - b
a = a - b
print("a = ",a)
print("b = ",b)

a =  3
b =  5


# **Strings in Python**

* Any data within double quotes `" "` or single quotes `' '` is treated as a string in Python.


In [ ]:
myString = 'Python is Fun!'
myString = "Python is Fun!"

* A multiline string can be assigned to a variable using three quotes.

In [ ]:
myMultiString = """This is
a multiline
string."""
print(myMultiString)

This is 
a multiline 
string.


* Using this as a workaround, we can simply enclose code between three quotes (single or double) to commment them. Python will treat it as a string which is not assigned to any variable and will hence ignore it.


In [ ]:
'''
print("Hello!")
print("World")
'''
print("I Love Python!")

I Love Python!


* Python is packed with many string ***methods*** which make working with strings very easy.

In [ ]:
s1 = "Thisisastring"

# Formatting
print(s1.upper())
print(s1.lower())
print(s1.swapcase())
print()

# Boolean checks
print(s1.isalpha())
print(s1.isnumeric())

THISISASTRING
thisisastring
tHISISASTRING

True
False


## **`split()` and `join()` string methods**

* `split()` : Splits the string in chunks separated by the input arguement.
* `join()` : Joins the items in iterable given as arguement, with the calling string as separator and returns new string.

In [ ]:
sample = "Python_is_Fun!"
stringList = sample.split('_')   #Default separator is ' '
print(stringList)

['Python', 'is', 'Fun!']


In [ ]:
separator = "_"
joinedStr = "++++".join(stringList)  # stringList is a python iterable
print(joinedStr)

Python++++is++++Fun!


# **Python Loops**




## **While Loop**
* The while loop will execute the code block as long as the given condition is true.

In [ ]:
counter = 10
while counter > 0:
    print(counter, end=' ')
    counter -= 1                # Python does not support counter --

10 9 8 7 6 5 4 3 2 1 

### `break` statement :
 Used to break out of the loop without the loop condition being evaluated to false.

In [ ]:
counter = 10
while counter > 0:
    print(counter, end=' ')
    if counter == 5:
        break
    counter -= 1
#print('\n',counter) Can anyone guess the value of the counter here?

10 9 8 7 6 5 
 5


### `continue` statement:
Used to *continue* the next iteration of the loop without executing the lines after this statement.


In [ ]:
counter = 10
while counter > 0:
    if counter%2 == 1:
        counter -= 1
        continue                    # Can you spot a bug in this code ?
    print(counter, end=' ')
    counter -= 1

10 8 6 4 2 0 

### `else` statement in Loop

In python, we can write an `else` block after the loop. This block is executed once the loop condition evaluates to false.

In [ ]:
counter = 10
while counter > 0:
    print(counter, end=' ')
    break
    counter -= 1
else:
    print("\nFinal Counter:", counter)

10 

* If `break` statement is used to exit loop, `else` block will NOT be executed.

## **For Loop**
* The for loop is usually executed for a range of numbers or items.


In [ ]:
lang = ["Python", "C", "Ruby", "Java"]
for x in lang:             # x serves as a temp variable
    print(x)

Python
C
Ruby
Java


In [ ]:
# Looping through a string
for c in "India":
  print(c)

I
n
d
i
a


### **`range()` function**

* The `range(start, end, step)` function is used to create a sequence of numbers from `start` to `end` with an increment of `step`.
* `end` is not included in the sequence.

`range()` can be used in three ways:

In [ ]:
# If only a single arguement is given, range defaults start value to 0.
# Value of step is taken 1 by default.

for i in range(5):
    print(i, end=" ")

0 1 2 3 4 

In [ ]:
for i in range(2, 7):
    print(i, end=" ")

2 3 4 5 6 

In [ ]:
for i in range(10, 4, -1):
    print(i, end=" ")

10 9 8 7 6 5 

In [ ]:
ls = [0, 1, 2, 3]
for i in range(len(ls)):
    print(ls[i])

0
1
2
3


## Coding Problem-2

In [7]:
# Create a program that prints the first 10 numbers of the Fibonacci sequence.
n = 1
last = 0
for i in range(10):
    print(last, " ")
    c = last
    last = n
    n = n + c

0  
1  
1  
2  
3  
5  
8  
13  
21  
34  


# **Python Collections**

## **Lists**

* Python lists are used to store multiple items in a single variable.
* An important point about lists is that they can comprise of multiple types of variables.
* Lists are 0-indexed and any list item can be accessed using this index.
* List items are mutable (changeable).

In [ ]:
myList = [10, 'ListItem', 14.5, 10j]
print(type(myList[0]), type(myList[1]), type(myList[2]), type(myList[3]))

# We can get the length of a list (or any other iterable) using len()
print("Length of List:", len(myList))

<class 'int'> <class 'str'> <class 'float'> <class 'complex'>
Length of List: 4


### **List Indexing**

* Lists are 0-indexed.
* Python also supports negative indexing. In negative indexing, the last item is assigned index `-1` and decreases by 1 as we move towards the first item.

In [ ]:
ls = [10, 20, 30, 40, 50, 60]

print(ls[5], ls[-1])
print(ls[4], ls[-2])
print(ls[0], ls[-6])

60 60
50 50
10 10


* Python also supports range indexing to get a range of items from a list.
* The range index is of the form `[i:j]`, which returns items from index `i` to `j-1` excluding item at index `j`

In [ ]:
fruits = ["apple", "mango", "orange", "kiwi", "banana", "cherry", "melon"]

print(fruits[1:3])      # Elements [1] and [2] are printed.

['mango', 'orange']


In [ ]:
# If first index is left empty, it will default to first index, i.e 0.
print(fruits[:3])

['apple', 'mango', 'orange']


In [ ]:
# If last index is left empty, it will default to last index.
print(fruits[1:])

['mango', 'orange', 'kiwi', 'banana', 'cherry', 'melon']


In [ ]:
# Negative indexing can also be used here
print(fruits[-4:-2])

print(fruits[-2:-4]) # What will this print? and Why? # Can you rectify this?

['kiwi', 'banana']
[]


* A double colon syntax can also be used for slicing lists. It is of the format `[start : stop : steps]`. The `steps` is the value incremented in each step.


In [ ]:
print(fruits[1:5:2])

['mango', 'kiwi']


* This can be used to reverse lists. Using a negative value for `steps` will iterate the list in reverse fashion.

In [ ]:
print(fruits[4:1:-1])

['banana', 'kiwi', 'orange']


In [ ]:
# We can reverse the entire list using this
print(fruits[::-1])
print(fruits)

['melon', 'cherry', 'banana', 'kiwi', 'orange', 'mango', 'apple']
['apple', 'mango', 'orange', 'kiwi', 'banana', 'cherry', 'melon']


### **Adding Items**

* Items can be added to lists using `append()` and `insert()`.

In [ ]:
ls = [10, 20, 30]

ls.append(40)       # Append adds an element to the end of the list.
print(ls)

[10, 20, 30, 40]


In [ ]:
ls = [10, 20, 40]

ls.insert(2, 30)      # .insert(index, value)
print(ls)

[10, 20, 30, 40]


* We can even add another list entirely.

In [ ]:
ls1 = [10, 20, 30]
ls2 = [40, 50, 60]

# Simply + operator can be used
ls3 = ls1 + ls2
print(ls3)


# .extend() method can be used to add elements from any iterable
ls1 = [10, 20, 30]
ls1.extend(ls2)     # A new list is not returned, ls2 is appended to ls1
print(ls1)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60]


### **Removing Items**

* The remove() method removes the specified item.

In [ ]:
ls = ["India", "Pakistan", "USA"]
ls.remove("Pakistan")
print(ls)

['India', 'USA']


* The pop() method removes the item at given index. If not specified, the last item is removed

In [ ]:
ls = ["India", "Pakistan", "USA"]
x = ls.pop()
print(ls)
print(x)

['India', 'Pakistan']
USA


* clear() method deletes all elements of the list

In [19]:
ls = ["Pakistan", "USA", "Russia"]
ls.clear()
print(ls)

[]


In [18]:
# Similarly del also can be used.
ls = ["Pakistan", "USA", "Russia"]
del ls[0]
print(ls)

del ls
#print(ls)

['USA', 'Russia']


### **Sorting**

* Sorting operation can be done by simply using the sort() method.
* By default, sorting is done in ascending order. For descending order, we set the arguement `reverse = True`

In [17]:
ls = [3, 5, 1, 2, 6, 7, -4, 5]
ls.sort()                  # Inplace sorting
print(ls)

[-4, 1, 2, 3, 5, 5, 6, 7]


In [16]:
ls = [3, 5, 1, 2, 6, 7, -4, 5]
ls.sort(reverse=True)       # Reverse sorting
print(ls)

[7, 6, 5, 5, 3, 2, 1, -4]


In [15]:
# For creating a new variable, we can use the sorted() function.
ls = [3, 5, 1, 2, 6, 7, -4, 5]
print(sorted(ls))
print(ls)

[-4, 1, 2, 3, 5, 5, 6, 7]
[3, 5, 1, 2, 6, 7, -4, 5]


> Python supports a lot of methods for lists. You can refer to these methods here.
https://www.w3schools.com/python/python_lists_methods.asp

####List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [8]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [9]:
# newList = [expression(element) for element in Oldlist if condition]
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [12]:
# Make a list of even square numbers using nums
squares = []
for x in nums:
  if(x**2 % 2 == 0):
    squares.append(x**2)

for y in squares:
  print(y, end=" ")


0 4 16 

In [13]:
# Make a list of even numbers between 1 to 10 using list comprehension
squares = []
for x in range(0,10):
  if(x % 2 == 0):
    print(x, end =" ")


0 2 4 6 8 

## **Sets**

* Set is an unordered collection of unique items.
* Duplicates are not allowed in sets. If a duplicate item is assigned, it is only inserted once.
* A set can be created using curly braces `{ }`.
* Sets items are not changeable, but the set itself can change. (i.e items can be added or removed)(Mutable)
* Items in the set cannot be replaced or changed.

* They are unindexed and so items cannot be accessed using index.

In [14]:
mySet = {10, 15, "v", 2, 13, "Hello", 10, 2, "v"}
print(mySet)

{2, 'Hello', 10, 13, 'v', 15}


### **Accessing Set Items**
* You cannot access items in a set by referring to an index or key.
But you can ask if a specified value is present in a set, by using the **in** keyword.

In [20]:
myLang = {"C++", "Python", "Java", "Kotlin"}
if "Javascript" in myLang:
    print("I know Javascript.")
else:
    print("I do not know Javascript.")

I do not know Javascript.


### **Adding Items**

* Items can be added to a set using `add()` method.

In [21]:
mySet = {10, 20, 30}
mySet.add(40)
print(mySet)

mySet.add(30)
print(mySet)

{40, 10, 20, 30}
{40, 10, 20, 30}


* To add multiple items at once, we can use `update()` method. It takes any iterable as an arguement.

In [23]:
mySet = {"A", "B", "C"}
ls = ["C", "D", "E"]

mySet.update(ls)
print(mySet)

{'B', 'D', 'A', 'C', 'E'}


### **Removing Items**

* To remove an item from set, we can use `discard()` or `remove()` method.
* Both function similarly with the only difference being that if item does not exist in the set, `remove()` will generate an error whereas `discard()` will NOT generate an error.

In [24]:
mySet = {10, 20, 'A', 'B'}
mySet.remove(10)
mySet.discard(30)         # Element does not exist.
print(mySet)

{'A', 20, 'B'}


In [25]:
mySet = {10, 20, 'A', 'B'}
mySet.discard(10)
mySet.discard(30)        # Element does not exist.
print(mySet)

{'A', 20, 'B'}


### **Set Operations**

* The `union()` method is used to perform union of two sets.
* The `intersection()` method is used to perform intersection of two sets.

In [26]:
A = {10, 20, 30}
B = {20, 40, 50, 60}

AuB = A.union(B)          # A new set is returned.
print(AuB)
AiB = A.intersection(B)         # A new set is returned.
print(AiB)

{50, 20, 40, 10, 60, 30}
{20}


* Many other operations like difference and symmetric difference can also be performed using set methods. Check reference : https://www.w3schools.com/python/python_sets_methods.asp

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

## **Dictionaries**

* Dictionaries are used to store `key : value` pairs in python. It is an implementation of hash tables.
* Item values can be accessed using the `key` for the required item.
* Dictionaries are mutable, i.e we can add or remove items after the dictionary has been created.
* Dictionaries require a unique `key` for every item. No two items can have the same `key`.


In [28]:
myDict = {
    "Student ID" : 202103017,         # keys and values can be of any data type
    "Name" : "Dhruv",
    "College" : "DAIICT",
    "Graduation Year" : 2025,
    "Years of Study" : [2021, 2022, 2023, 2024],
}
print(myDict)
print(myDict["Name"])

{'Student ID': 202103017, 'Name': 'Dhruv', 'College': 'DAIICT', 'Graduation Year': 2025, 'Years of Study': [2021, 2022, 2023, 2024]}
Dhruv


### **Accessing Dictionary Items**

* As shown above, dictionary `values` can be accessed by using their corresponding `keys` as index.
* This can also be done using the `get()` method. This will prevent an error incase key does not exist.

In [27]:
gradeDict = {'A' : 5, 'B': 4, 'C' : 3, 'D' : 2, 'E' : 1, 'F' : 0}

print(gradeDict['A'])
print(gradeDict.get('B'))
print(gradeDict.get('X'))

5
4
None


### **Adding and Updating Items**

* Existing items can be updated easily by accessing them using their corresponding `key`.

In [29]:
phone = {
    'Company' : 'Samsung',
    'Model' : 'S21',
    'Android Version' : 11
}

phone['Android Version'] = 12
print(phone)

{'Company': 'Samsung', 'Model': 'S21', 'Android Version': 12}


* If we assign a `value` to a `key` which does not exist, a new `key : value` pair will be added to the dictionary.

In [30]:
phone = {
    'Company' : 'Samsung',
    'Model' : 'S21',
    'Android Version' : 11
}
phone['OneUI'] = 4.1
print(phone)

{'Company': 'Samsung', 'Model': 'S21', 'Android Version': 11, 'OneUI': 4.1}


* To add new or update multiple items at once, we can use the `update()` method of dictionaries.
* `update()` method takes a dictionary as input which will be merged with the calling dictionary.

In [31]:
phone = {
    'Company' : 'Samsung',
    'Model' : 'S21',
    'Android Version' : 11
}
phone.update({'Model':'S22', 'Android Version':12, 'Color': 'Black'})
print(phone)

{'Company': 'Samsung', 'Model': 'S22', 'Android Version': 12, 'Color': 'Black'}


### **Remove Items**

* To remove an item, we can use the `pop()` method. It takes item `key` as input parameter.

In [32]:
phone = {
    'Company' : 'Samsung',
    'Model' : 'S21',
    'Android Version' : 12,
    'Color' : 'Black'
}
phone.pop('Color')
print(phone)

{'Company': 'Samsung', 'Model': 'S21', 'Android Version': 12}


* The `popitem()` method removes the last inserted item from the dictionary.

* Note that dictionaries are unordered in versions before 3.7. In older versions, this method removes a random item.

In [33]:
phone = {
    'Company' : 'Samsung',
    'Model' : 'S21',
    'Android Version' : 12,
}
phone.popitem()
print(phone)

{'Company': 'Samsung', 'Model': 'S21'}


### **Items, Keys & Values**

While using python dictionaries you will work with these three terms.
1. ***items*** : Items refer to a `key:value` pair. It is stored in the form of a tuple.
2. ***keys*** : Keys refer to the user made indices which are used to access items.
3. ***values*** : Values refere to the *data* which can be accessed using its corresponding key.

We can view all items, keys and values using the methods `items()`, `keys()`

and `values()` respectively.

In [ ]:
phone = {
    'Company' : 'Samsung',
    'Model' : 'S21',
    'Android Version' : 12,
}

print(phone.items(), type(phone.items()))
print(phone.keys(), type(phone.keys()))
print(phone.values(), type(phone.values()))

dict_items([('Company', 'Samsung'), ('Model', 'S21'), ('Android Version', 12)]) <class 'dict_items'>
dict_keys(['Company', 'Model', 'Android Version']) <class 'dict_keys'>
dict_values(['Samsung', 'S21', 12]) <class 'dict_values'>


> Python dictionaries also support many other methods. Check reference: https://www.w3schools.com/python/python_dictionaries_methods.asp

## **Tuples**

* Tuples are used to store multiple items in a single variable.
* Tuples are created using `( )` and are immutable (unchangeable)
* Similar to lists, tuples are 0-indexed.

In [35]:
myTuple = ("Zero", "One", "Two", "Three")
print(myTuple)


('Zero', 'One', 'Two', 'Three')


In [ ]:
myTuple[0] = "Five"

TypeError: ignored

In [34]:
# A tuple can also have different data type values
diffTup = (0, "One", 2.0)
print(type(diffTup[0]), type(diffTup[1]), type(diffTup[2]))

<class 'int'> <class 'str'> <class 'float'>


* As tuples are unchangeable, we cannot add or remove elements from a tuple.
But there is a workaround for this. We can convert the tuple into a list, add/remove your item, and then convert it back into a tuple.

In [38]:
thistuple=("apple","banana","cherry")
print(thistuple)
y=list(thistuple)
y.append("orange")
thistuple=tuple(y)
print(thistuple)

('apple', 'banana', 'cherry')
('apple', 'banana', 'cherry', 'orange')


### **Unpacking tuples**

* As we discussed tuples are used to store multiple items in a single variable. Now, unpacking a tuple means creating a separate variable for every item in a tuple.

In [40]:
myTuple = ("Zero", "One", "Two")
z, o, t = myTuple
print(z, o, t, sep='\n')

Zero
One
Two


* If number of variables created are not equal to the number of items in the tuple, we will face an error. To resolve this error, use `*` before a variable name to assign all remaining items to that variable as a list.

In [39]:
myTuple = ("Zero", "One", "Two")
*z, o = myTuple      # Use *
print(z,o)

['Zero', 'One'] Two


A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [41]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(d)
print(type(t))


{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
<class 'tuple'>


In [42]:
print(d[t])
print(d[(1, 2)])

5
1


# **Functions in Python**

* Functions in python can be declared using the `def` keyword.
* `def` is followed by function name and arguements within `( )`.

In [44]:
def myFunction(username):
    print("Welcome", username)

myFunction("Dhruv")

Welcome Dhruv


In [43]:
# Multiple Arguements
def myFunc(username, email):
    print("Username:", username)
    print("Email ID:", email)

myFunc("Dhruv", "dhruv@mail.com")

Username: Dhruv
Email ID: dhruv@mail.com


* For multiple parameters, arguements can also be sent in the form of `key = value` synatax.

In [45]:
def myFunc(username, email):
    print("Username:", username)
    print("Email ID:", email)

myFunc(email="dhruv@mail.com", username="Dhruv")

Username: Dhruv
Email ID: dhruv@mail.com


# Classes in Python

In [46]:
# The Syntax for defining the classes is pretty straightforward.

class Greeter:
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred!
HELLO, FRED


## Coding Problem - 3

In [51]:
# Create a function that checks if a given string is a palindrome.
# Your Code here.
def ispalindrome(s):
  n = len(s)
  for x in range(len(s)):
    if(s[x] != s[x-n]):
      print("String is not Palindrome")
      break
    else:
      continue

ispalindrome("abcde")

In [59]:
# Create a program that removes duplicate elements from a list.
# Your Code here.
def remove_duplicates(data):
  return list(set(data))


my_list = [1, 2, 2, 3, 4, 4, 5]
unique_list = remove_duplicates(my_list)
print(unique_list)


[1, 2, 3, 4, 5]


In [58]:
# Write a class representing a simple bank account with methods to deposit, withdraw, and check balance.
# Your Code here.
class account:


  def __init__(self,balance):
    self.balance = balance

  def deposit(self, Deposit):
    self.balance += Deposit

  def withdraw(self, Withdraw):
    self.balance -= Withdraw

  def display(self):
    print("Current Balance: ", self.balance)


a = account(5000)
a.deposit(1000)
a.display()
a.withdraw(3000)
a.display()


Current Balance:  6000
Current Balance:  3000


# **Python pip**


* Python supports a lot of third-party packages which can be easily installed using pip.
* **pip** is a package installer for python.
* Note that pip is not a python function. It is a command line tool which is used to manage packages in python.

## **Installing a package**

* If you have python installed on your local machine, you can try using pip on your command prompt.

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


* You can find numerous useful python packages at https://pypi.org/

## **Using a package**

* To use a package in python, we need to first import it to our code using the `import` and `from` keyword.



In [60]:
from math import sqrt
x=3
y=4
z=sqrt(x**2+y**2)
print(z)

5.0


# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# **Extending Python Using NumPy**

* Due to the way that a Python list is implemented, accessing items in a large list is computationally expensive.

*   The main problem with the list is that, to allow a list to have non-uniform data types, each item in the list is stored in a memory location, with the list containing an "array" of pointers to each of these locations.   
*  In NumPy, an array is of type `ndarray` (n-dimensional array), and all the elements must be of the same type.



# Creating NumPy Arrays

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
a1=np.arange(10) #Created a range from 0 to 9
print(a1)
print(a1.shape)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
(10,)


* To create an array of a specific size filled with 0's, we use the zeros() function.

In [2]:
a2= np.zeros(5) # Creates an array with all 0's
print(a2)
print(a2.shape)

[0. 0. 0. 0. 0.]
(5,)


* We can also create two-dimensional arrays using the zeros() function

In [3]:
a3=np.zeros((2,3)) #Array with 2 rows and 3 columns; This array has all zeros.
print(a3.shape)
print(a3)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


* If we want an array filled with a specific number instead of 0, use the `full()` function

In [4]:
a4= np.full((3,3),8)
print(a4)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


* The `eye()` function returns a 2-D array with ones on the diagonal and zeros elsewhere. For eg.

In [5]:
a5= np.eye(4) # 4x4 identity matrix
print(a5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* To create an array filled with random numbers, we can use the `random()` function from the `numpy.random` module.

In [6]:
a6= np.random.random((2,4)) # A 2x4 Array with random values.
print(a6)

[[0.83563765 0.77796861 0.09844245 0.13067355]
 [0.82484528 0.18225152 0.32454231 0.08147674]]



# Array Indexing

* Accessing elements in the array is similar to accessing elements in a Python List.

In [7]:
list1= [1,2,3,4,5]
list2= [6,7,8,9,0]
r1 = np.array([list1,list2])
print(r1)
print(r1.shape) # 2 rows and 5 columns
print(r1[0,0])
print(r1[0,1])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2


## Boolean Indexing

In [8]:
r2=np.array(list1)
print(r2)
print(r2>2) # Prints a list containing boolean values.
print(r2[r2>2]) # [3,4,5]

#Write a code to list all the odd numbers from a list of numbers using boolean indexing.
nums= np.arange(10)
print(nums)
odd_nums= nums[nums%2==1]
print(odd_nums)


[1 2 3 4 5]
[False False  True  True  True]
[3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## Slicing Arrays

* Very important feature of NumPy, very useful in ML.
* Similar to Python List.

In [9]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


* Slicing has the syntax: `start:stop`. So for a 2-D array it becomes:  `[start:stop, start:stop]`

In [10]:
# We will extract the last two rows and the first two columns using slicing.
b1 = a[0:,:2] #row 1 to the last row, and the first 2 columns
print(b1)



[[ 1  2]
 [ 6  7]
 [11 12]]


In [11]:
#With negative indexing
b2= a[-3:,-5:-3]
print(b2)

[[ 1  2]
 [ 6  7]
 [11 12]]


Point to Note: Result of slicing is dependent on how you slice it. For eg.


In [12]:
b3=a[2:,:] # row 2 onwards and all columns.
print(b3)
print(b3.shape) # Here the result is rank 2. # Rank is simply the number of dimensions(or axes) an array has

[[11 12 13 14 15]]
(1, 5)


In [13]:
b4=a[2,:]
print(b4)
print(b4.shape)

[11 12 13 14 15]
(5,)


## Reshaping the Arrays

* You can reshape the arrays to other dimensions using the `reshape()` keyword.

In [14]:
b4 = b4.reshape(1,-1) # First arguement indicates the number of rows.
                      # -1 indicates that we leave it to the reshape() function to create the correct number of columns.
                      # You can also specify the number of columns in the second argument
print(b4)
print(b4.shape)

[[11 12 13 14 15]]
(1, 5)


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example

In [15]:
# Given a matrix X which is (nx1), we want to make a matrix such that
''' [1, x1, (x1)^2, (x1)^3, ......, (xn)^n
     1, x2, (x2)^2, (x2)^3, ......, (xn)^n
     ...................
     .
     .
     .
     .
     .
     1, xn, (xn)^2, (xn)^3, ......., (xn)^n]
'''
#Give a Brute Force Approach using for l


X = np.array([1,2,3,4,5]).reshape(5,1)
print(X.shape)
pow = np.arange(0,len(X))
mat = X ** pow
print(mat)

(5, 1)
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


## Coding Problem-4


In [18]:
## Write a program that creates a 3x3 matrix with values ranging from 1 to 9. Then, modify the matrix by doubling the values of the second row.

# Your Code here.

import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

matrix[1, :] *= 2
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 8 10 12]
 [ 7  8  9]]


# **Let's Code: Hangman Game**

> Hangman is a simple paper-pencil, word-guessing game where the player must guess the given word within a certain number of guesses.
Let's code a simple hangman game in python!



In [41]:
import random

fig = ["\n ____\n|     \n|    O\n|       \n|     \n|       \n",
       "\n ____\n|     \n|    O\n|    |  \n|    |\n|       \n",
       "\n ____\n|     \n|    O\n|   /|  \n|    |\n|       \n",
       "\n ____\n|     \n|    O\n|   /|\\n|    |\n|       \n",
       "\n ____\n|     \n|    O\n|   /|\\n|    |\n|   /   \n",
       "\n ____\n|     \n|    O\n|   /|\\n|    |\n|   / \\n",
       "\n ____\n|    |\n|    O\n|   /|\\n|    |\n|   / \\n"]

# Your Code here. Please avoid using Chat-GPT :)
# Brownie points for those who will implement the game using Object Oriented Programming Concepts.

class Game:

    def __init__(self, word_list):
        self.word_list = word_list
        self.fig = fig

    def choose_word(self):
        return random.choice(self.word_list)[0]

    def get_hint(self, target):
        """Provides a relevant hint based on the chosen word's category in the word list."""

        for word, category in self.word_list:
            if word == target:
                return f"Hint: The word is related to {category}."
        return "Hint: No category available."

    def display(self, target, guesses):
        return ' '.join([letter if letter in guesses else '_' for letter in target])

    def play(self):
        target = self.choose_word()
        guesses = set()
        wrong = 0

        print("Welcome to Hangman!")
        hint = self.get_hint(target)
        print(hint)

        while wrong < 6:
            print(self.fig[wrong])
            print("Word:", self.display(target, guesses))
            print("Guessed letters:", ' '.join(sorted(guesses)))
            cg = input("Enter a character: ").lower()

            if cg in guesses:
                print("You already guessed that letter.")
            elif cg in target:
                guesses.add(cg)
                print("Correct Guess.")
            else:
                guesses.add(cg)
                wrong += 1
                print("Incorrect Guess.")

            if all(letter in guesses for letter in target):
                print("\n Congratulations! You won!!")
                print("The word was:", target)
                return

        print(self.fig[6])
        print("You Lost. The word was:", target)


if __name__ == "__main__":
    words = [("python", "Programming Language"), ("january", "month"), ("history", "Subject")]
    start = Game(words)
    start.play()


Welcome to Hangman!
Hint: The word is related to Subject.

 ____
|     
|    O
|       
|     
|       

Word: _ _ _ _ _ _ _
Guessed letters: 
Enter a character: h
Correct Guess.

 ____
|     
|    O
|       
|     
|       

Word: h _ _ _ _ _ _
Guessed letters: h
Enter a character: i
Correct Guess.

 ____
|     
|    O
|       
|     
|       

Word: h i _ _ _ _ _
Guessed letters: h i
Enter a character: s
Correct Guess.

 ____
|     
|    O
|       
|     
|       

Word: h i s _ _ _ _
Guessed letters: h i s
Enter a character: t
Correct Guess.

 ____
|     
|    O
|       
|     
|       

Word: h i s t _ _ _
Guessed letters: h i s t
Enter a character: o
Correct Guess.

 ____
|     
|    O
|       
|     
|       

Word: h i s t o _ _
Guessed letters: h i o s t
Enter a character: r
Correct Guess.

 ____
|     
|    O
|       
|     
|       

Word: h i s t o r _
Guessed letters: h i o r s t
Enter a character: y
Correct Guess.

 Congratulations! You won!!
The word was: history


For more examples on python and numpy, you can also go through the following tutorial.

https://cs231n.github.io/python-numpy-tutorial/
